model_params:
  latent_dim: 20
  hidden_channels: [64, 128, 256]
  in_channels: 1

data_params:
  data_name: dsprites
  datapath: "/home/victorchen/workspace/Venus/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz"
  input_size: [64, 64]
  # data_name: mnist
  # datapath: "/home/victorchen/workspace/Venus/torch_download"
  # input_size: [32, 32]
  batch_size: 512
  shuffle: true
  grid_nrow: 32
  num_workers: 4

training_params:
  epochs: 60
  lr: 0.0001
  use_cuda: true
  optimizer: adam
  betas: [0.9, 0.999]
  momentum: 0.0
  lr_decay_weight: 0.5
  decay_step: 20

save_params:
  num_iter_save_model: 2
